pipeline {
    agent any
    environment {
        AWS_ACCOUNT_ID="361752933564"
        AWS_DEFAULT_REGION="ap-south-1"
        IMAGE_REPO_NAME="x-non-prod-ecr"
        IMAGE_NAME="x-app"
        REPOSITORY_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}"
        BRANCH=getBranch()
        DEPLOY_TAG="${BRANCH}_${GIT_COMMIT}"
        CONTAINER_IMAGE="${REPOSITORY_URI}:${DEPLOY_TAG}"
    }
    stages {
        // Logging into AWS ECR
        stage('Logging into AWS ECR') {
            steps {
                script {
                    sh "aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
                }
            }
        }

        // Building Docker images
        stage('Building image') {
            steps {
                dir('.') {
                    sh "docker build -t ${IMAGE_NAME}:${BRANCH} . "
                    }
            }
        }

        // Pushing to ECR
        stage('Pushing to ECR') {
            steps {
                script {
                    sh "docker tag ${IMAGE_NAME}:${BRANCH} ${CONTAINER_IMAGE}"
                    sh "docker push ${CONTAINER_IMAGE}"
                }
            }
        }
    }
}
