pipeline {
    agent { node { label 'jenkins-slave' } }
    environment {
        AWS_ACCOUNT_ID="361752933564"
        AWS_DEFAULT_REGION="ap-south-1"
        IMAGE_REPO_NAME="x-non-prod-ecr"
        IMAGE_NAME="x-app"
        IMAGE_TAG="latest"
        
        REPOSITORY_URI = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}"
    }

    stages {
        // Logging into AWS ECR
        stage('Logging into AWS ECR') {
            steps {
                script {
                    sh "aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
                }
            }
        }

        // Building Docker images
        stage('Building image') {
            steps {
                script {
                    dockerImage = docker.build "${IMAGE_NAME}:${IMAGE_TAG}", "--file website/Dockerfile ."
                }
            }
        }

        // Pushing to ECR
        stage('Pushing to ECR') {
            steps {
                script {
                    // Print environment variables
                    sh 'printenv'

                    def branchName = env.BRANCH_NAME
                    def jobId = env.BUILD_ID
                    def commitId = env.GIT_COMMIT

                    def tag = "${branchName}_${IMAGE_NAME}_${IMAGE_TAG}_${jobId}_${commitId}"

                    // Additional tag for stage
                    def additionalTag = "${branchName}_${IMAGE_NAME}"

                    // Push to kpi-website ECR repository for both main and stage branches
                    sh "docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${REPOSITORY_URI}:${tag}"
                    sh "docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${REPOSITORY_URI}:${additionalTag}"
                    
                    sh "docker push ${REPOSITORY_URI}:${tag}"
                    sh "docker push ${REPOSITORY_URI}:${additionalTag}"

                    // Output job ID and Commit ID
                    echo "Job ID: ${jobId}"
                    echo "Commit ID: ${commitId}"
                }
            }
        }
    }
}

def getAgentLabel() {
    if (env.BRANCH_NAME == 'stage') {
        return 'kpi-web-stage'
    } else (env.BRANCH_NAME == 'prod') {
        return 'kpi-web-prod'
    }
}